In [1]:
import pandas as pd
import os

In [2]:
def extract_placements(dir):
    files = os.listdir(dir)

    placements = {1: [], 2: [], 3: [], 4: [], "qfs": []}
    for file in files:
        df = pd.read_csv(os.path.join(dir, file))

        # Get the winner
        final_row = df.iloc[-1]
        assert final_row["stage"] == "Final"
        sim_winner  = final_row["winner"]
        sim_finalist = final_row["home"] if final_row["home"] != sim_winner else final_row["away"]
        placements[1].append(sim_winner)
        placements[2].append(sim_finalist)

        # Get the other semifinalists (third place match)
        third_place_match_row = df.iloc[-2]
        assert third_place_match_row["stage"] == "Third"
        sim_third = third_place_match_row["winner"]
        sim_fourth = third_place_match_row["home"] if third_place_match_row["home"] != sim_third else third_place_match_row["away"]
        placements[3].append(sim_third)
        placements[4].append(sim_fourth)

        # Get the other quarterfinalists
        quarterfinal_rows = df.iloc[-8:-4]
        sim_quarterfinalists = quarterfinal_rows["home"].tolist() + quarterfinal_rows["away"].tolist()
        sim_quarterfinalists = [q for q in sim_quarterfinalists if q not in [sim_winner,sim_finalist,sim_third,sim_fourth]]
        placements["qfs"].append(sim_quarterfinalists)

    return placements

In [3]:
def aggregate_stats(placements):
    # Winners
    winners = pd.Series(placements[1])
    TOTAL_SIMULATIONS = len(winners)
    print("Total simulations: ", TOTAL_SIMULATIONS)
    winners_prob = pd.DataFrame(winners.value_counts() / TOTAL_SIMULATIONS).rename(columns={"count": "win_prob"})

    # Semi-Finalists
    semifinalists = pd.Series(placements[1]+placements[2]+placements[3]+placements[4])
    assert len(semifinalists) == 4 * TOTAL_SIMULATIONS
    semifinalists_prob = pd.DataFrame(semifinalists.value_counts() / TOTAL_SIMULATIONS).rename(columns={"count": "sf_prob"})

    # Quarter-Finalists (flatten the qfs list of lists)
    quarterfinalists = pd.Series(placements[1]+placements[2]+placements[3]+placements[4]+[c for sim in placements["qfs"] for c in sim])
    assert len(quarterfinalists) == 8 * TOTAL_SIMULATIONS
    quarterfinalists_prob = pd.DataFrame(quarterfinalists.value_counts() / TOTAL_SIMULATIONS).rename(columns={"count": "qf_prob"})

    # Join together
    simulation_prob = quarterfinalists_prob.merge(
        semifinalists_prob, left_index=True, right_index=True, how="outer"
    ).merge(
        winners_prob, left_index=True, right_index=True, how="outer"
    )
    return simulation_prob.sort_values(by=["win_prob","sf_prob"], ascending=False)

# ELO-based simulations

In [4]:
# Load data
placements_elo = extract_placements("simulation_results/elo")

In [5]:
simulation_elo_prob = aggregate_stats(placements_elo)
simulation_elo_prob

Total simulations:  10000

                        qf_prob  sf_prob  win_prob
Spain                    0.7553   0.6936    0.4159
Argentina                0.7206   0.5814    0.2438
France                   0.6845   0.5262    0.1307
England                  0.5554   0.3609    0.0612
Portugal                 0.4166   0.1809    0.0291
Brazil                   0.4389   0.2480    0.0267
Colombia                 0.3888   0.1662    0.0229
Netherlands              0.4321   0.1830    0.0149
Ecuador                  0.2803   0.1434    0.0091
Germany                  0.2683   0.1345    0.0085
Norway                   0.2583   0.1070    0.0064
Turkey                   0.3364   0.0743    0.0057
Japan                    0.2862   0.0972    0.0053
Croatia                  0.2092   0.0870    0.0051
Belgium                  0.3384   0.0649    0.0032
Switzerland              0.2734   0.0683    0.0030
Mexico                   0.2375   0.0686    0.0029
Uruguay                  0.1353   0.0526    0.0029
Senegal                  0.1395   0.0400    0.0010
Morocco                  0.1077   0.0230    0.0005
Paraguay                 0.1309   0.0227    0.0005
Austria                  0.0571   0.0123    0.0003
Scotland                 0.0559   0.0101    0.0002
South Korea              0.1053   0.0135    0.0001
Iran                     0.0684   0.0085    0.0001
Canada                   0.0875   0.0107       NaN
Australia                0.0480   0.0063       NaN
Czechia                  0.0351   0.0035       NaN
Algeria                  0.0289   0.0030       NaN
Panama                   0.0187   0.0017       NaN
Sweden                   0.0168   0.0017       NaN
Uzbekistan               0.0101   0.0015       NaN
United States            0.0166   0.0011       NaN
Ivory Coast              0.0183   0.0009       NaN
Egypt                    0.0171   0.0007       NaN
Bosnia and Herzegovina   0.0107   0.0003       NaN
Jordan                   0.0043   0.0003       NaN
DR Congo                 0.0020   0.0002       NaN
Cape Verde               0.0008      NaN       NaN
Haiti                    0.0002      NaN       NaN
Iraq                     0.0003      NaN       NaN
New Zealand              0.0009      NaN       NaN
Saudi Arabia             0.0013      NaN       NaN
South Africa             0.0003      NaN       NaN
Tunisia                  0.0018      NaN       NaN

# Odds-based simulations

In [6]:
# Load data
placements_odds = extract_placements("simulation_results/odds")

In [7]:
simulation_odds_prob = aggregate_stats(placements_odds)
simulation_odds_prob

Total simulations:  10000

                        qf_prob  sf_prob  win_prob
Spain                    0.6826   0.5699    0.2262
France                   0.6812   0.5177    0.2061
England                  0.7048   0.4568    0.1446
Portugal                 0.6934   0.4449    0.1258
Argentina                0.6028   0.3777    0.0928
Brazil                   0.5377   0.3030    0.0809
Germany                  0.3718   0.2326    0.0443
Netherlands              0.4373   0.1807    0.0267
Norway                   0.3069   0.1301    0.0114
Belgium                  0.4475   0.1283    0.0108
United States            0.3300   0.0989    0.0087
Colombia                 0.2559   0.1103    0.0061
Mexico                   0.2128   0.0593    0.0033
Morocco                  0.2248   0.0616    0.0032
Uruguay                  0.1614   0.0524    0.0024
Japan                    0.1726   0.0464    0.0024
Turkey                   0.1751   0.0423    0.0010
Switzerland              0.1716   0.0401    0.0010
Ecuador                  0.0858   0.0221    0.0008
Croatia                  0.1139   0.0364    0.0007
Canada                   0.1210   0.0219    0.0002
Austria                  0.0590   0.0121    0.0002
Sweden                   0.0550   0.0088    0.0002
Senegal                  0.0748   0.0129    0.0001
Egypt                    0.0424   0.0056    0.0001
Bosnia and Herzegovina   0.0525   0.0057       NaN
South Korea              0.0552   0.0052       NaN
Scotland                 0.0302   0.0042       NaN
Ivory Coast              0.0249   0.0027       NaN
Algeria                  0.0187   0.0022       NaN
Paraguay                 0.0161   0.0016       NaN
Iran                     0.0191   0.0013       NaN
Czechia                  0.0190   0.0012       NaN
Ghana                    0.0143   0.0010       NaN
Australia                0.0094   0.0007       NaN
Tunisia                  0.0046   0.0005       NaN
Saudi Arabia             0.0024   0.0004       NaN
DR Congo                 0.0050   0.0003       NaN
Panama                   0.0008   0.0001       NaN
Uzbekistan               0.0013   0.0001       NaN
Cape Verde               0.0005      NaN       NaN
Haiti                    0.0003      NaN       NaN
Iraq                     0.0002      NaN       NaN
Jordan                   0.0003      NaN       NaN
New Zealand              0.0008      NaN       NaN
Qatar                    0.0005      NaN       NaN
South Africa             0.0018      NaN       NaN

# Combine simulations

In [ ]:
compare_simulation_prob = simulation_elo_prob.merge(
    simulation_odds_prob,
    left_index=True,
    right_index=True,
    suffixes=("_elo", "_odds"),
    how="outer"
)
compare_simulation_prob[["qf_prob_elo", "qf_prob_odds", "sf_prob_elo", "sf_prob_odds", "win_prob_elo", "win_prob_odds"]] = \
    compare_simulation_prob[["qf_prob_elo", "qf_prob_odds", "sf_prob_elo", "sf_prob_odds", "win_prob_elo", "win_prob_odds"]].fillna(0)

compare_simulation_prob["qf_prob_avg"] = compare_simulation_prob[["qf_prob_elo", "qf_prob_odds"]].mean(axis=1)
compare_simulation_prob["sf_prob_avg"] = compare_simulation_prob[["sf_prob_elo", "sf_prob_odds"]].mean(axis=1)  # LOOK AT THIS
compare_simulation_prob["win_prob_avg"] = compare_simulation_prob[["win_prob_elo", "win_prob_odds"]].mean(axis=1)

# A combination (average) of ELO-based and odds-based simulations ->
# -> taking the P(getting to the semifinals)/4, assuming it's a tossup who wins once you reach the SF.
compare_simulation_prob["win_prob_avg_any_of_the_semifinalists"] = compare_simulation_prob["sf_prob_avg"] / 4
# Turns out extremely similar to Opta predictions: https://theanalyst.com/articles/who-will-win-2026-fifa-world-cup-predictions-opta-supercomputer

compare_simulation_prob.sort_values(by=["win_prob_avg_any_of_the_semifinalists", "win_prob_avg", "sf_prob_avg"], ascending=False)

,qf_prob_elo,sf_prob_elo,win_prob_elo,qf_prob_odds,sf_prob_odds,win_prob_odds,qf_prob_avg,sf_prob_avg,win_prob_avg,win_prob_avg_any_of_the_semifinalists
Spain,0.7553,0.6936,0.4159,0.6826,0.5699,0.2262,0.71895,0.63175,0.32105,0.157938
France,0.6845,0.5262,0.1307,0.6812,0.5177,0.2061,0.68285,0.52195,0.16840,0.130488
Argentina,0.7206,0.5814,0.2438,0.6028,0.3777,0.0928,0.66170,0.47955,0.16830,0.119888
England,0.5554,0.3609,0.0612,0.7048,0.4568,0.1446,0.63010,0.40885,0.10290,0.102212
Portugal,0.4166,0.1809,0.0291,0.6934,0.4449,0.1258,0.55500,0.31290,0.07745,0.078225
Brazil,0.4389,0.2480,0.0267,0.5377,0.3030,0.0809,0.48830,0.27550,0.05380,0.068875
Germany,0.2683,0.1345,0.0085,0.3718,0.2326,0.0443,0.32005,0.18355,0.02640,0.045887
Netherlands,0.4321,0.1830,0.0149,0.4373,0.1807,0.0267,0.43470,0.18185,0.02080,0.045463
Colombia,0.3888,0.1662,0.0229,0.2559,0.1103,0.0061,0.32235,0.13825,0.01450,0.034562
Norway,0.2583,0.1070,0.0064,0.3069,0.1301,0.0114,0.28260,0.11855,0.00890,0.029637
Belgium,0.3384,0.0649,0.0032,0.4475,0.1283,0.0108,0.39295,0.09660,0.00700,0.024150
Ecuador,0.2803,0.1434,0.0091,0.0858,0.0221,0.0008,0.18305,0.08275,0.00495,0.020688
Japan,0.2862,0.0972,0.0053,0.1726,0.0464,0.0024,0.22940,0.07180,0.00385,0.017950
Mexico,0.2375,0.0686,0.0029,0.2128,0.0593,0.0033,0.22515,0.06395,0.00310,0.015987
Croatia,0.2092,0.0870,0.0051,0.1139,0.0364,0.0007,0.16155,0.06170,0.00290,0.015425
Turkey,0.3364,0.0743,0.0057,0.1751,0.0423,0.0010,0.25575,0.05830,0.00335,0.014575
Switzerland,0.2734,0.0683,0.0030,0.1716,0.0401,0.0010,0.22250,0.05420,0.00200,0.013550
Uruguay,0.1353,0.0526,0.0029,0.1614,0.0524,0.0024,0.14835,0.05250,0.00265,0.013125
United States,0.0166,0.0011,0.0000,0.3300,0.0989,0.0087,0.17330,0.05000,0.00435,0.012500
Morocco,0.1077,0.0230,0.0005,0.2248,0.0616,0.0032,0.16625,0.04230,0.00185,0.010575
Senegal,0.1395,0.0400,0.0010,0.0748,0.0129,0.0001,0.10715,0.02645,0.00055,0.006613
Canada,0.0875,0.0107,0.0000,0.1210,0.0219,0.0002,0.10425,0.01630,0.00010,0.004075
Austria,0.0571,0.0123,0.0003,0.0590,0.0121,0.0002,0.05805,0.01220,0.00025,0.003050
Paraguay,0.1309,0.0227,0.0005,0.0161,0.0016,0.0000,0.07350,0.01215,0.00025,0.003038
South Korea,0.1053,0.0135,0.0001,0.0552,0.0052,0.0000,0.08025,0.00935,0.00005,0.002338
Scotland,0.0559,0.0101,0.0002,0.0302,0.0042,0.0000,0.04305,0.00715,0.00010,0.001788
Sweden,0.0168,0.0017,0.0000,0.0550,0.0088,0.0002,0.03590,0.00525,0.00010,0.001313
Iran,0.0684,0.0085,0.0001,0.0191,0.0013,0.0000,0.04375,0.00490,0.00005,0.001225
Australia,0.0480,0.0063,0.0000,0.0094,0.0007,0.0000,0.02870,0.00350,0.00000,0.000875
Egypt,0.0171,0.0007,0.0000,0.0424,0.0056,0.0001,0.02975,0.00315,0.00005,0.000788
Bosnia and Herzegovina,0.0107,0.0003,0.0000,0.0525,0.0057,0.0000,0.03160,0.00300,0.00000,0.000750
Algeria,0.0289,0.0030,0.0000,0.0187,0.0022,0.0000,0.02380,0.00260,0.00000,0.000650
Czechia,0.0351,0.0035,0.0000,0.0190,0.0012,0.0000,0.02705,0.00235,0.00000,0.000588
Ivory Coast,0.0183,0.0009,0.0000,0.0249,0.0027,0.0000,0.02160,0.00180,0.00000,0.000450
Panama,0.0187,0.0017,0.0000,0.0008,0.0001,0.0000,0.00975,0.00090,0.00000,0.000225
Uzbekistan,0.0101,0.0015,0.0000,0.0013,0.0001,0.0000,0.00570,0.00080,0.00000,0.000200
Ghana,0.0000,0.0000,0.0000,0.0143,0.0010,0.0000,0.00715,0.00050,0.00000,0.000125
DR Congo,0.0020,0.0002,0.0000,0.0050,0.0003,0.0000,0.00350,0.00025,0.00000,0.000063
Tunisia,0.0018,0.0000,0.0000,0.0046,0.0005,0.0000,0.00320,0.00025,0.00000,0.000063
Saudi Arabia,0.0013,0.0000,0.0000,0.0024,0.0004,0.0000,0.00185,0.00020,0.00000,0.000050
Jordan,0.0043,0.0003,0.0000,0.0003,0.0000,0.0000,0.00230,0.00015,0.00000,0.000037
Cape Verde,0.0008,0.0000,0.0000,0.0005,0.0000,0.0000,0.00065,0.00000,0.00000,0.000000
Haiti,0.0002,0.0000,0.0000,0.0003,0.0000,0.0000,0.00025,0.00000,0.00000,0.000000
Iraq,0.0003,0.0000,0.0000,0.0002,0.0000,0.0000,0.00025,0.00000,0.00000,0.000000
New Zealand,0.0009,0.0000,0.0000,0.0008,0.0000,0.0000,0.00085,0.00000,0.00000,0.000000
Qatar,0.0000,0.0000,0.0000,0.0005,0.0000,0.0000,0.00025,0.00000,0.00000,0.000000
South Africa,0.0003,0.0000,0.0000,0.0018,0.0000,0.0000,0.00105,0.00000,0.00000,0.000000

In [11]:
compare_simulation_prob.shape

(47, 10)